name: mykulka
description: Your własna kulka.
version: 1.0.0+1
publish_to: 'none'



environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"


flutter:
  uses-material-design: true
  assets: 
    - lib/assets/img/root/
  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic

        - asset: lib/assets/fonts/Rubik-Regular.ttf
        - asset: lib/assets/fonts/Rubik-Italic.ttf
          style: italic
        
        - asset : lib/assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset : lib/assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic

        - asset : lib/assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset : lib/assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: lib/assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic

        - asset : lib/assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset : lib/assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: lib/assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset : lib/assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21 